# Generated by Django 6.0.5 on 2026-05-18 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0002_seed_alphabet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="notes",
        ),
    ]
