# Generated by Django 6.0.5 on 2026-05-18 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0003_remove_card_notes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="attempt",
            name="flashcards__card_id_e05d59_idx",
        ),
        migrations.DeleteModel(
            name="Attempt",
        ),
    ]
