# Generated by Django 6.0.5 on 2026-05-19 09:27

import flashcards.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0005_chapters_three_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="audio_english",
            field=models.FileField(
                blank=True, null=True, upload_to=flashcards.models._audio_upload_path
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="audio_georgian",
            field=models.FileField(
                blank=True, null=True, upload_to=flashcards.models._audio_upload_path
            ),
        ),
    ]
