# Generated by Django 6.0.5 on 2026-05-19 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0006_card_audio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="audio_english",
        ),
    ]
