# Generated by Django 6.0.5 on 2026-05-25 18:21

import django.db.models.deletion
import flashcards.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0007_remove_card_audio_english"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonWordChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CommonWordCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("georgian", models.CharField(max_length=255)),
                ("english", models.CharField(max_length=255)),
                ("romanised", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "audio_georgian",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=flashcards.models._common_word_audio_upload_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="flashcards.commonwordchapter",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
